### rest echo test
GET http://localhost:8090/echo?msg=node.js&title=hello

### rest echo test
GET http://localhost:8090/sum?a=1&b=2

### rest echo test
GET http://localhost:8090/sub?a=1&b=2

### rest echo test
GET http://localhost:8090/avg?a=1&b=2&c=3&d=4&e=5
